### ISSUE TITLE
The included urlconf doesn't have any patterns in it

### ISSUE THREAD

**Issue by jirah** [RyanBalfanz/django-launch-page#2]
Hi,

I installed django-launch-page using pip, and this erros is showing of:

ImproperlyConfigured at /launch_page/
The included urlconf <module 'launch_page.urls' from /usr/local/lib/python2.7/dist-packages/launch_page/urls.py'> doesn't have any patterns in it

Can you please help me?

Thanks.

**Comment by RyanBalfanz** [comment]
@jirah, Have you had a chance to look at the installation section in the README or at the example project? Let me know if you're still having trouble.
